### ISSUE TITLE
ATOMIC_UPDATE called from host function

### ISSUE THREAD

**Issue by ilagunap** [LLNL/Quicksilver#34]
In file MC_SourceNow.cc:

`ATOMIC_CAPTURE` and `ATOMIC_UPDATE` macros are used inside a host function: `void MC_SourceNow(MonteCarlo *monteCarlo)`. When the macro (defined in AtomicMacro.hh) is evaluated under a CUDA compiler (e.g., nvcc or clang) the code checks whether `__CUDA_ARCH__` is defined or not and tries to replace it by the CUDA version or the serial version.

Under a CUDA compiler, because `__CUDA_ARCH__` is always defined, it will try to replace the macro with the device version, but this is incorrect because the function is a host function.

**Comment by bleile1** [comment]
"Under a CUDA compiler, because `__CUDA_ARCH__` is always defined, it will try to replace the macro with the device version, but this is incorrect because the function is a host function."

This is not true in previous versions of NVCC. Unless there has been a recent change, then `__CUDA_ARCH__` is only defined during the `__device__` pass of the compilation of functions.

i.e. for host code `__CUDA_ARCH__` evaluated to undefined.

**Comment by ilagunap** [comment]
@bleile1 You are right, according to the CUDA programing guide the macro is defined on device code only. There must be a bug in clang then. When I compile with clang it tries to use the device functions, I'm not sure why (see the error below).

I think I can close this issue since it's apparently a clang problem and nvcc works find on this.

Clang error:

```
clang++ -x cuda --cuda-gpu-arch=sm_60 -DHAVE_CUDA -std=c++11 -O0 -g -fcuda-rdc -c MC_SourceNow.cc -o MC_SourceNow.o
MC_SourceNow.cc:92:3: error: no matching function for call to 'atomicAdd'
                ATOMIC_CAPTURE( cell._sourceTally, 1, random_number_seed );
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./AtomicMacro.hh:34:17: note: expanded from macro 'ATOMIC_CAPTURE'
            p = atomicAdd( &x, v );
                ^~~~~~~~~
/usr/tce/packages/cuda/cuda-9.2.148/include/device_atomic_functions.hpp:76:38: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE_ATOMIC_FUNCTIONS_DECL__ int atomicAdd(int *address, int val)
                                     ^
/usr/tce/packages/cuda/cuda-9.2.148/include/device_atomic_functions.hpp:81:47: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE_ATOMIC_FUNCTIONS_DECL__ unsigned int atomicAdd(unsigned int *address, unsigned int val)
                                              ^
/usr/tce/packages/cuda/cuda-9.2.148/include/device_atomic_functions.hpp:196:57: note: candidate function not viable: call to __device__ function from __host__ function
__DEVICE_ATOMIC_FUNCTIONS_DECL__ unsigned long long int atomicAdd(unsigned long long int *address, unsigned long long int val)
                                                        ^
/usr/tce/packages/cuda/cuda-9.2.148/include/sm_20_atomic_functions.hpp:76:39: note: candidate function not viable: call to __device__ function from __host__ function
__SM_20_ATOMIC_FUNCTIONS_DECL__ float atomicAdd(float *address, float val)
                                      ^
/usr/tce/packages/cuda/cuda-9.2.148/include/sm_60_atomic_functions.hpp:78:40: note: candidate function not viable: call to __device__ function from __host__ function
__SM_60_ATOMIC_FUNCTIONS_DECL__ double atomicAdd(double *address, double val)
```
