### ISSUE TITLE
Application Output Explenation

### ISSUE THREAD

**Issue by Yiltan** [LLNL/Quicksilver#46]
Is there any documentation to explain the output of this application? I am trying to understand how to interpret the data. From searching the code I can see that the first column refers to parts of the code which was timed.

```
Timer                       Cumulative   Cumulative   Cumulative   Cumulative   Cumulative   Cumulative
Name                            number    microSecs    microSecs    microSecs    microSecs   Efficiency
                              of calls          min          avg          max       stddev       Rating
main                                 1    1.529e+06    1.531e+06    1.533e+06    1.402e+03        99.90
cycleInit                           10    1.988e+05    2.750e+05    3.871e+05    7.559e+04        71.04
cycleTracking                       10    1.137e+06    1.251e+06    1.329e+06    7.726e+04        94.15
cycleTracking_Kernel            669680    5.383e+05    7.237e+05    8.906e+05    1.507e+05        81.27
cycleTracking_MPI               736648    7.518e+04    1.453e+05    2.153e+05    6.100e+04        67.49
cycleTracking_Test_Done          66978    2.151e+03    2.499e+03    3.023e+03    3.242e+02        82.67
cycleFinalize                       20    4.660e+02    9.270e+02    1.362e+03    3.434e+02        68.06
Figure Of Merit              1.938e+07 [Num Segments / Cycle Tracking Time]
```

**Comment by richards12** [comment]
Yiltan,

I think the column headers are fairly clear.
Column 2 is the number of times the corresponding code region was called.
Columns 3-6 refer to the total time spent in each code region where
  3: min total time over all MPI ranks
  4: avg total time for all  MPI ranks
  5: max total time over all MPI ranks
  6: standard deviation of the distribution over all ranks.

Column 7  is an estimate of how imbalanced the ranks are in the corresponding regions.  You could get the exact formula from the code.

Hope this helps,

Dave

-------------------
David Richards
Center for Applied Scientific Computing
Lawrence Livermore National Laboratory

**Comment by Yiltan** [comment]
Thank you Dave, I assumed as much but wanted to double check that they were timing measurements.

Thanks for the help!
